#!/usr/bin/with-contenv bash

PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc

echo "
-------------------------------------
   __ _| |_ __ (_)_ __   ___ 
  / _` | | '_ \| | '_ \ / _ \
 | (_| | | |_) | | | | |  __/
  \__,_|_| .__/|_|_| |_|\___|
         |_|                
-------------------------------------
GID/UID
-------------------------------------
User uid:    $(id -u abc)
User gid:    $(id -g abc)
-------------------------------------
"
chown abc:abc /app
chown abc:abc /config
chown abc:abc /defaults
